dist: xenial
language: python
python:
- '3.5'

install:
- pip install pipenv
- pipenv sync --dev

script:
- pipenv run python setup.py build
- pipenv run make -C doc html SOURCEDIR=api
- pipenv run flake8
- pipenv run doc8
