dist: xenial
language: python
python:
- '3.5'

install:
- pip install poetry
- poetry install

script:
- poetry run python setup.py build
- poetry run make -C doc html SOURCEDIR=api
- poetry run flake8
- poetry run doc8
