[tool.poetry]
name = "pybricks-api"
version = "2.0.0"
description = "Documentation and user-API for Pybricks MicroPython"
authors = ["Laurens Valk <laurens@pybricks.com>", "David Lechner <david@pybricks.com>" ]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.5"

[tool.poetry.dev-dependencies]
doc8 = "*"
flake8 = "*"
sphinx = "==1.7.9"
sphinx-rtd-theme = "==0.4.3"
sphinxcontrib-contentui = "==0.2.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
